config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  get 'awaiting_confirmation', to: 'users#confirmation', as: 'confirm_user'

  root to: "projects#index"
  
  resources :files

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  namespace :admin do
    root to: "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  put '/admin/users/:user_id/permissions',
        to: 'admin/permissions#update',
        as: :update_user_permissions
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
	
	has_many :tickets, dependent: :destroy

  validates :name, presence: true

  has_many :permissions, as: :thing
	scope :readable_by, lambda { |user| joins(:permissions).where(permissions: 
																{ action: "view", user_id: user.id }) }

	def self.for(user)
		user.admin? ? Project : Project.readable_by(user)		
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authorize_admin!, except: [:index, :show]
	before_filter :authenticate_user!, only: [:index, :show]
	before_filter :find_project, only: [:show, :edit, :update, :destroy]

	def index
		@projects = Project.for(current_user).all
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(params[:project])
		if @project.save
			redirect_to @project, notice: "Project has been created."
		else
			flash[:alert] = "Project has not been created."
			render action: "new"
		end
	end

	def show
		@tickets = @project.tickets
	end

	def edit
	end

	def update
		if @project.update_attributes(params[:project])
			redirect_to @project, notice: "Project has been updated."
		else
			flash[:alert] = "Project has not been updated."
			render action: "edit"
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path, notice: "Project has been deleted."
	end	

	private
		
		def find_project
			@project = Project.for(current_user).find(params[:id])
			rescue ActiveRecord::RecordNotFound
			redirect_to projects_path, alert: "The project you were looking for could not be found."
		end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for(@project) do |f|
	= f.error_messages
	%p
		= f.label :name
		= f.text_field :name
	= f.submit

app/views/projects/edit.html.haml
%h2 Edit project
= render "form"

app/views/projects/index.html.haml
%h2 Projects
%ul#projects
	- @projects.each do |project|
		%li= link_to project.name, project
		= admins_only do
			%li= link_to "New Project", new_project_path

app/views/projects/new.html.haml
%h2 New project
= render "form"

app/views/projects/show.html.haml
- title(@project.name, "Projects")

%h2= @project.name
= admins_only do
	= link_to "Edit Project", edit_project_path(@project)
	= link_to "Delete Project", @project, method: :delete, 
						data: { confirm: "Are you sure you want to delete this project?" }

- authorized?(:"create tickets", @project) do
	= link_to "New Ticket", new_project_ticket_path(@project)

= form_tag search_project_tickets_path(@project), method: :get do
	= label_tag "search"
	= text_field_tag "search", params[:search]
	= submit_tag "Search"

%ul#tickets
	- unless @tickets.is_a?(Class)
		- @tickets.each do |ticket|
			%li
				= render ticket.state if ticket.state
				\##{ ticket.id } - #{ link_to ticket.title, [@project, ticket] }