config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  get 'awaiting_confirmation', to: 'users#confirmation', as: 'confirm_user'

  root to: "projects#index"
  
  resources :files

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  namespace :admin do
    root to: "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  put '/admin/users/:user_id/permissions',
        to: 'admin/permissions#update',
        as: :update_user_permissions
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, 
  			 :rememberable, :trackable, :validatable, :confirmable
  
  has_many :permissions

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def to_s
  	"#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :find_user, only: [:show, :edit, :update, :destroy]

  def index
  	@users = User.all(order: "email")
  end

  def show
  end
  
  def new
    @user = User.new
  end

  def create
    admin = params[:user].delete(:admin) 
    @user = User.new(params[:user])
    if @user.save && @user.update_attribute("admin", admin == "1")
      redirect_to admin_users_path, notice: "User has been created."
    else
      flash[:alert] = "User has not been created."
      render action: "new"
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end
    admin = params[:user].delete(:admin) 
    if @user.update_attributes(params[:user]) && @user.update_attribute("admin", admin == "1")
      redirect_to admin_users_path, notice: "User has been updated."
    else
      flash[:alert] = "User has not been updated."
      render action: "edit"
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end
    redirect_to admin_users_path
  end


  private
    def find_user
      @user = User.find(params[:id])      
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def confirmation
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
	= f.error_messages
	%p
		= f.label :email
		= f.text_field :email
	%p
		= f.label :password
		= f.password_field :password
	%p
		= f.check_box :admin
		= f.label :admin, "Is an admin?"
	= f.submit

app/views/admin/users/edit.html.haml
= render "form"

app/views/admin/users/index.html.haml
= link_to "New User", new_admin_user_path
%ul
	- @users.each do |user|
		%li= link_to user, [:admin, user]

app/views/admin/users/new.html.haml
%h2 New User
= render "form"

app/views/admin/users/show.html.haml
%h2= @user
= link_to "Edit User", edit_admin_user_path(@user)
= link_to "Delete User", admin_user_path(@user), method: :delete, 
		data: { confirm: "Are you sure you want to delete this user?"} 
= link_to "Permissions", admin_user_permissions_path(@user)