config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  get 'awaiting_confirmation', to: 'users#confirmation', as: 'confirm_user'

  root to: "projects#index"
  
  resources :files

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  namespace :admin do
    root to: "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  put '/admin/users/:user_id/permissions',
        to: 'admin/permissions#update',
        as: :update_user_permissions
  

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :background, :color, :name, :default
	
	def to_s
    name
  end

  def default!
  	current_default_state = State.find_by_default(true)

  	self.default = true
  	self.save!

  	if current_default_state
  		current_default_state.default = false
  		current_default_state.save!
  	end
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController

	def index
		@states = State.all
	end

	def new
		@state = State.new
	end
	
	def create
		@state = State.new(params[:state])
		if @state.save
			redirect_to admin_states_path, notice: "State has been created."
		else
			flash[:alert] = "State has not been created."
			render action: "new"
		end
	end

	def make_default
		@state = State.find(params[:id])
		@state.default!
		redirect_to admin_states_path, notice: "#{@state.name} is now the default state."		
	end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.haml
= form_for [:admin, @state] do |f|
	%p
		= f.label 			:name
		= f.text_field 	:name
	= f.submit

app/views/admin/states/index.html.haml
= link_to "New State", new_admin_state_path

%ul#states
	- @states.each do |state|
		%li{ id: "state_#{state.id}" }
			= state.name
			- if state.default?
				(Default)
			- else
				= link_to "Make default", make_default_admin_state_path(state)

app/views/admin/states/new.html.haml
%h1 New State
= render "form"